# Copyright 2023 The Tongsuo Project Authors. All Rights Reserved.
#
# Licensed under the Apache License 2.0 (the "License").  You may not use
# this file except in compliance with the License.  You can obtain a copy
# in the file LICENSE in the source distribution or at
# https://github.com/Tongsuo-Project/tongsuo-mini/blob/main/LICENSE

name: GitHub CI

on: [pull_request, push]

permissions:
  contents: read

jobs:
  minimal:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install packages
      run: |
        sudo apt-get update
        sudo apt-get -y install cmake python3 python3-pip python3-pytest
      # TODO
      # because of local development using act forbidden by firewall,
      # install cmake manually and simplify python & pytest env setup
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build
    - name: Build
      run: cmake --build ${{github.workspace}}/build
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

  with_single_module:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: [asn1, sm3, sm4]
    steps:
    - uses: actions/checkout@v3
    - name: install packages
      run: |
        sudo apt-get update
        sudo apt-get -y install cmake python3 python3-pip python3-pytest
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build
    - name: Build
      run: cmake --build ${{github.workspace}}/build -DWITH_${{matrix.module}}=ON
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

  all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install packages
      run: |
        sudo apt-get update
        sudo apt-get -y install cmake python3 python3-pip python3-pytest
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build
    - name: Build
      run: cmake --build ${{github.workspace}}/build -DWITH_ALL=ON
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
